name: appointment-service
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
   build :
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }}  

     # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Log in to AWS ECR using AWS credentials
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

     # Build the Docker image
    - name: Build Docker image
      run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }} src/appointment
      
      # Tag the Docker image with the ECR repository URI
    - name: Tag Docker image
      run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker tag ${{ secrets.ECR_REPOSITORY }} $IMAGE_URI

      # Push the Docker image to ECR
    - name: Push Docker image to Amazon ECR
      run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker push $IMAGE_URI

    

    
          
  
