name: appointment-service
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
   build :
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }}  

     # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Log in to AWS ECR using AWS credentials
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    
          
  
